//new books
export const SET_BOOKS_REQUEST = "SET_BOOKS_REQUEST";
export const SET_BOOKS_SUCCESS = "SET_BOOKS_SUCCESS";
export const SET_BOOKS_FAILED = "SET_BOOKS_FAILED";

//search 
export const SET_SEARCH_BOOK_REQUEST = "SET_SEARCH_BOOK_REQUEST";
export const SET_SEARCH_BOOK_SUCCESS = "SET_SEARCH_BOOK_SUCCESS";
export const SET_SEARCH_BOOK_FAILED = "SET_SEARCH_BOOK_FAILED";